/* ============================================================
   quiz-data.js — Bộ câu hỏi trắc nghiệm cho từng pattern.
   Key = tên file (bỏ .html). Mỗi câu: {q, options[], correct, explanation}
   ============================================================ */
window.QUIZ = {
  /* ============== CREATIONAL ============== */
  "singleton": [
    { q: "Mục đích cốt lõi của Singleton là gì?",
      options: ["Đảm bảo một lớp chỉ có đúng một thể hiện và cung cấp điểm truy cập toàn cục",
        "Tạo ra nhiều thể hiện giống hệt nhau", "Sao chép đối tượng nhanh hơn", "Ẩn giao diện phức tạp của hệ thống con"],
      correct: 0, explanation: "Singleton giới hạn một lớp ở đúng MỘT thể hiện, truy cập qua getInstance()." },
    { q: "getInstance() lần thứ hai trả về gì?",
      options: ["Một thể hiện mới", "null", "Đúng thể hiện đã tạo ở lần đầu (cùng tham chiếu)", "Một bản clone"],
      correct: 2, explanation: "Lần đầu mới tạo (lazy), các lần sau luôn trả lại cùng một thể hiện." },
    { q: "Nhược điểm thường gặp của Singleton là gì?",
      options: ["Tốn nhiều RAM", "Khó test và tạo phụ thuộc ẩn (global state)", "Không thể kế thừa", "Luôn chậm hơn new"],
      correct: 1, explanation: "Trạng thái toàn cục làm khó unit test và giấu phụ thuộc giữa các module." }
  ],
  "factory": [
    { q: "Factory Method giải quyết vấn đề gì?",
      options: ["Tạo đối tượng mà không lộ lớp cụ thể cho phía dùng", "Đảm bảo chỉ có một thể hiện",
        "Gộp nhiều lệnh thành một", "Duyệt tập hợp phần tử"],
      correct: 0, explanation: "Client gọi phương thức tạo, lớp con quyết định tạo đối tượng cụ thể nào." },
    { q: "Ai quyết định loại sản phẩm cụ thể được tạo?",
      options: ["Client trực tiếp new", "Lớp con override phương thức factory", "Constructor của interface", "Trình biên dịch"],
      correct: 1, explanation: "Các lớp con (subclass) override factory method để chọn sản phẩm cụ thể." },
    { q: "Nguyên tắc thiết kế nào Factory Method hỗ trợ mạnh nhất?",
      options: ["Single Responsibility", "Dependency Inversion — phụ thuộc vào trừu tượng, không phải lớp cụ thể",
        "Interface Segregation", "Law of Demeter"],
      correct: 1, explanation: "Client phụ thuộc interface sản phẩm, tách khỏi lớp cụ thể → Dependency Inversion." }
  ],
  "abstract-factory": [
    { q: "Abstract Factory khác Factory Method chủ yếu ở điểm nào?",
      options: ["Tạo MỘT HỌ đối tượng liên quan khớp nhau, không chỉ một sản phẩm",
        "Chỉ dùng cho Singleton", "Không dùng interface", "Luôn tạo đối tượng ngẫu nhiên"],
      correct: 0, explanation: "Abstract Factory tạo cả họ sản phẩm nhất quán (vd nguyên liệu NY vs Chicago)." },
    { q: "Vì sao dùng Abstract Factory thay vì new trực tiếp từng thành phần?",
      options: ["Để đảm bảo các thành phần trong cùng họ luôn tương thích với nhau",
        "Để tiết kiệm bộ nhớ", "Để chạy nhanh hơn", "Để tránh dùng interface"],
      correct: 0, explanation: "Một factory cụ thể chỉ tạo các sản phẩm cùng bộ → tránh trộn lẫn không tương thích." },
    { q: "Thêm một 'họ sản phẩm' mới đòi hỏi điều gì?",
      options: ["Sửa toàn bộ client", "Tạo một lớp factory cụ thể mới implement interface factory",
        "Xoá interface", "Không làm được"],
      correct: 1, explanation: "Chỉ cần thêm một concrete factory mới, client dùng qua interface không đổi." }
  ],
  "builder": [
    { q: "Builder phù hợp nhất khi nào?",
      options: ["Khi dựng đối tượng phức tạp qua nhiều bước tuỳ chọn", "Khi chỉ cần một thể hiện",
        "Khi cần clone nhanh", "Khi duyệt danh sách"],
      correct: 0, explanation: "Builder tách quá trình dựng từng bước khỏi biểu diễn cuối cùng." },
    { q: "Phương thức build() thường làm gì?",
      options: ["Xoá đối tượng", "Trả về đối tượng hoàn chỉnh sau khi cấu hình xong",
        "Reset builder về mặc định", "Tạo một builder khác"],
      correct: 1, explanation: "build() lắp ráp và trả về sản phẩm cuối từ các bước đã set." },
    { q: "Kỹ thuật 'method chaining' (fluent) trong Builder nghĩa là gì?",
      options: ["Mỗi bước set trả về chính builder để gọi nối tiếp", "Gọi build nhiều lần",
        "Chạy các bước song song", "Ẩn constructor"],
      correct: 0, explanation: "Mỗi setter return this nên viết được .setA().setB().build() liền mạch." }
  ],
  "prototype": [
    { q: "Prototype tạo đối tượng mới bằng cách nào?",
      options: ["Clone (sao chép) từ một đối tượng mẫu có sẵn", "Gọi new với đầy đủ tham số",
        "Đọc từ file", "Dùng Singleton"],
      correct: 0, explanation: "Prototype nhân bản một mẫu thay vì khởi tạo lại từ đầu." },
    { q: "Khi nào Prototype có lợi rõ rệt?",
      options: ["Khi khởi tạo đối tượng rất tốn kém và ta chỉ cần thay đổi vài thuộc tính",
        "Khi cần đúng một thể hiện", "Khi không có dữ liệu", "Khi duyệt cây"],
      correct: 0, explanation: "Clone rẻ hơn dựng lại toàn bộ khi cấu hình ban đầu phức tạp/đắt." },
    { q: "Điểm cần lưu ý khi clone là gì?",
      options: ["Không bao giờ được clone", "Phân biệt shallow copy và deep copy để tránh chia sẻ tham chiếu ngoài ý muốn",
        "Clone luôn nhanh hơn new tuyệt đối", "Phải dùng kèm Facade"],
      correct: 1, explanation: "Shallow copy chia sẻ đối tượng con; deep copy nhân bản cả cây con." }
  ],

  /* ============== STRUCTURAL ============== */
  "adapter": [
    { q: "Adapter giải quyết vấn đề gì?",
      options: ["Cho hai interface không tương thích làm việc với nhau", "Giới hạn một thể hiện",
        "Thêm hành vi lúc chạy", "Chia lệnh đọc/ghi"],
      correct: 0, explanation: "Adapter bọc một lớp để nó khớp interface mà client mong đợi." },
    { q: "Trong ví dụ 'gà tây giả làm vịt', Adapter làm gì?",
      options: ["Biến gà tây thành vịt thật", "Bọc gà tây và chuyển gobble() thành quack() theo interface Duck",
        "Xoá con gà tây", "Tạo con vịt mới"],
      correct: 1, explanation: "Adapter implement interface Duck, bên trong gọi API của Turkey." },
    { q: "Adapter khác Decorator ở điểm nào?",
      options: ["Adapter đổi interface; Decorator giữ interface nhưng thêm hành vi",
        "Không khác gì", "Adapter luôn nhanh hơn", "Decorator đổi interface, Adapter thêm hành vi"],
      correct: 0, explanation: "Adapter chuyển đổi giao diện; Decorator bổ sung chức năng mà giữ nguyên giao diện." }
  ],
  "bridge": [
    { q: "Bridge tách rời điều gì?",
      options: ["Trừu tượng (abstraction) khỏi hiện thực (implementation) để hai bên biến đổi độc lập",
        "Đọc khỏi ghi", "Client khỏi server", "Model khỏi View"],
      correct: 0, explanation: "Bridge nối abstraction với implementation qua composition, đổi độc lập hai trục." },
    { q: "Vì sao Bridge chống 'bùng nổ lớp con'?",
      options: ["Vì gộp mọi thứ vào một lớp", "Vì kết hợp 2 trục bằng composition thay vì kế thừa chéo (m×n → m+n)",
        "Vì cấm kế thừa", "Vì dùng Singleton"],
      correct: 1, explanation: "Kế thừa chéo tạo m×n lớp; Bridge dùng composition nên chỉ m+n." },
    { q: "Ví dụ Remote điều khiển Device minh hoạ Bridge thế nào?",
      options: ["Remote (abstraction) giữ tham chiếu tới Device (implementation), đổi loại remote/device độc lập",
        "Remote kế thừa Device", "Device tạo Remote", "Remote là Singleton"],
      correct: 0, explanation: "Đổi loại điều khiển hoặc loại thiết bị mà không ảnh hưởng bên kia." }
  ],
  "composite": [
    { q: "Composite cho phép làm gì?",
      options: ["Xử lý đối tượng đơn lẻ (lá) và nhóm (nhánh) đồng nhất qua cùng interface",
        "Đảm bảo một thể hiện", "Đổi thuật toán lúc chạy", "Ẩn hệ thống con"],
      correct: 0, explanation: "Client dùng cùng một API cho cả phần tử lá và phần tử tổng hợp." },
    { q: "Cấu trúc dữ liệu tự nhiên của Composite là gì?",
      options: ["Cây (tree) phân cấp", "Hàng đợi", "Bảng băm", "Danh sách phẳng"],
      correct: 0, explanation: "Composite mô hình cấu trúc phần–toàn thể dạng cây, nhánh chứa lá/nhánh khác." },
    { q: "Ví dụ 'thực đơn lồng thực đơn' thể hiện điều gì?",
      options: ["Menu (nhánh) và MenuItem (lá) đều có thể print() như nhau",
        "Chỉ MenuItem mới in được", "Menu không chứa được menu con", "Phải viết vòng lặp riêng cho từng cấp"],
      correct: 0, explanation: "Duyệt đệ quy: gọi print() lên gốc tự lan xuống toàn bộ cây." }
  ],
  "decorator": [
    { q: "Decorator thêm chức năng bằng cách nào?",
      options: ["Bọc đối tượng gốc trong nhiều lớp trang trí, mỗi lớp thêm hành vi",
        "Sửa mã lớp gốc", "Kế thừa sâu nhiều tầng", "Dùng Singleton"],
      correct: 0, explanation: "Mỗi decorator bọc component và bổ sung hành vi trước/sau khi uỷ quyền." },
    { q: "Nguyên tắc thiết kế nào Decorator minh hoạ?",
      options: ["Open/Closed — mở để mở rộng, đóng để sửa đổi", "Singleton", "DRY", "YAGNI"],
      correct: 0, explanation: "Thêm chức năng bằng lớp mới (mở rộng) mà không sửa lớp gốc (đóng sửa đổi)." },
    { q: "Vì sao decorator và đối tượng gốc phải cùng interface?",
      options: ["Để client dùng chúng thay thế cho nhau và bọc lồng nhiều lớp",
        "Để chạy nhanh hơn", "Để tiết kiệm RAM", "Không cần cùng interface"],
      correct: 0, explanation: "Cùng interface nên decorator có thể bọc bất kỳ component nào, kể cả decorator khác." }
  ],
  "facade": [
    { q: "Facade cung cấp điều gì?",
      options: ["Một giao diện đơn giản cho một hệ thống con phức tạp", "Đúng một thể hiện",
        "Khả năng undo", "Nhiều họ sản phẩm"],
      correct: 0, explanation: "Facade gom các lệnh phức tạp thành API đơn giản (vd watchMovie())." },
    { q: "Facade có ẩn hoàn toàn hệ thống con không?",
      options: ["Có, khoá cứng không cho truy cập", "Không — vẫn cho phép dùng trực tiếp hệ thống con khi cần",
        "Chỉ ẩn một nửa", "Xoá hệ thống con"],
      correct: 1, explanation: "Facade chỉ đơn giản hoá lối vào phổ biến, không cấm truy cập sâu." },
    { q: "Facade khác Adapter ở chỗ nào?",
      options: ["Facade đơn giản hoá nhiều lớp; Adapter chuyển đổi một interface sang interface khác",
        "Giống hệt nhau", "Facade đổi interface, Adapter đơn giản hoá", "Cả hai đều là Singleton"],
      correct: 0, explanation: "Facade = tiện lợi cho hệ con; Adapter = làm khớp interface không tương thích." }
  ],
  "flyweight": [
    { q: "Flyweight tối ưu điều gì?",
      options: ["Bộ nhớ, bằng cách chia sẻ phần trạng thái dùng chung giữa nhiều đối tượng",
        "Tốc độ mạng", "Số dòng code", "Bảo mật"],
      correct: 0, explanation: "Flyweight tách trạng thái nội tại (chia sẻ) khỏi ngoại tại (riêng) để giảm RAM." },
    { q: "Trạng thái 'nội tại' (intrinsic) trong Flyweight là gì?",
      options: ["Phần dùng chung, không đổi, được chia sẻ", "Phần riêng của mỗi đối tượng",
        "Trạng thái toàn cục", "Trạng thái tạm"],
      correct: 0, explanation: "Nội tại = bất biến & chia sẻ; ngoại tại = truyền vào từ ngoài mỗi lần dùng." },
    { q: "Ví dụ 'trồng cả rừng cây' minh hoạ gì?",
      options: ["Nhiều cây chia sẻ chung dữ liệu loại cây (texture, hình), chỉ lưu riêng toạ độ",
        "Mỗi cây là một đối tượng đầy đủ độc lập", "Chỉ có một cây duy nhất", "Cây được clone"],
      correct: 0, explanation: "TreeType (chia sẻ) + vị trí riêng → hàng nghìn cây nhưng ít đối tượng nặng." }
  ],
  "proxy": [
    { q: "Proxy đóng vai trò gì?",
      options: ["Đại diện/kiểm soát truy cập tới một đối tượng khác", "Tạo họ sản phẩm",
        "Duyệt tập hợp", "Gộp lệnh"],
      correct: 0, explanation: "Proxy đứng trước đối tượng thật, kiểm soát và có thể thêm xử lý khi truy cập." },
    { q: "Virtual Proxy (proxy ảnh) hoạt động thế nào?",
      options: ["Hiện ảnh tạm và chỉ tải ảnh thật (tốn kém) khi thực sự cần",
        "Tải hết mọi ảnh ngay", "Không tải gì cả", "Xoá ảnh thật"],
      correct: 0, explanation: "Virtual proxy trì hoãn việc tạo đối tượng nặng đến khi cần (lazy)." },
    { q: "Loại proxy nào kiểm tra quyền truy cập?",
      options: ["Protection Proxy", "Remote Proxy", "Virtual Proxy", "Smart Reference"],
      correct: 0, explanation: "Protection proxy kiểm soát quyền; remote = mạng; virtual = lazy load." }
  ],

  /* ============== BEHAVIORAL ============== */
  "chain-of-responsibility": [
    { q: "Chain of Responsibility làm gì với một yêu cầu?",
      options: ["Chuyền qua chuỗi handler đến khi có handler xử lý được", "Gửi tới mọi handler cùng lúc",
        "Chỉ handler đầu tiên xử lý", "Xử lý ngẫu nhiên"],
      correct: 0, explanation: "Mỗi handler hoặc xử lý, hoặc chuyển tiếp cho handler kế trong chuỗi." },
    { q: "Lợi ích chính của pattern này là gì?",
      options: ["Tách rời người gửi khỏi người nhận cụ thể", "Đảm bảo một thể hiện",
        "Tăng tốc độ mạng", "Nén dữ liệu"],
      correct: 0, explanation: "Người gửi không cần biết ai xử lý; chuỗi có thể sắp xếp/thay đổi linh hoạt." },
    { q: "Ví dụ máy ATM nhả tiền minh hoạ thế nào?",
      options: ["Handler mệnh giá 500k → 200k → 100k... lần lượt nhả và chuyển phần dư xuống dưới",
        "Chỉ nhả toàn tờ nhỏ nhất", "Nhả tất cả cùng lúc", "Một handler làm hết"],
      correct: 0, explanation: "Mỗi handler xử lý phần mình rồi chuyển số dư cho mắt xích kế tiếp." }
  ],
  "command": [
    { q: "Command pattern đóng gói cái gì thành đối tượng?",
      options: ["Một yêu cầu/hành động (kèm receiver và tham số)", "Một tập hợp dữ liệu",
        "Một luồng sự kiện", "Một cấu hình"],
      correct: 0, explanation: "Command bọc lời gọi thành đối tượng có execute() (và thường undo())." },
    { q: "Vì sao Command hỗ trợ Undo dễ dàng?",
      options: ["Mỗi command biết cách đảo ngược hành động của chính nó (undo)",
        "Vì lưu toàn bộ màn hình", "Vì dùng Singleton", "Vì nó không đổi trạng thái"],
      correct: 0, explanation: "Command lưu đủ thông tin để thực thi và hoàn tác → undo/redo, hàng đợi, log." },
    { q: "Trong ví dụ điều khiển từ xa, 'invoker' là ai?",
      options: ["Nút bấm/remote gọi execute() mà không biết chi tiết receiver",
        "Thiết bị (đèn, quạt)", "Người dùng", "Command interface"],
      correct: 0, explanation: "Invoker (remote) chỉ gọi command.execute(); receiver là thiết bị thực thi." }
  ],
  "interpreter": [
    { q: "Interpreter pattern dùng để làm gì?",
      options: ["Định nghĩa ngữ pháp và thông dịch câu/biểu thức của một ngôn ngữ nhỏ",
        "Tạo đối tượng", "Chia đọc/ghi", "Chia sẻ bộ nhớ"],
      correct: 0, explanation: "Mỗi luật ngữ pháp thành một lớp; cây các lớp đó diễn giải biểu thức." },
    { q: "Cấu trúc cây trong Interpreter gọi là gì?",
      options: ["Abstract Syntax Tree (AST)", "B-Tree", "Cây đỏ đen", "Heap"],
      correct: 0, explanation: "Biểu thức được phân tích thành AST rồi gọi interpret() đệ quy." },
    { q: "Interpreter phù hợp nhất khi nào?",
      options: ["Ngôn ngữ đơn giản, ngữ pháp ổn định và không quá lớn",
        "Ngôn ngữ cực phức tạp cần hiệu năng cao", "Không có ngữ pháp", "Chỉ xử lý số"],
      correct: 0, explanation: "Với ngữ pháp phức tạp/lớn thì trình phân tích chuyên dụng tốt hơn Interpreter." }
  ],
  "iterator": [
    { q: "Iterator cung cấp khả năng gì?",
      options: ["Duyệt tuần tự các phần tử của tập hợp mà không lộ cấu trúc bên trong",
        "Sắp xếp tập hợp", "Nhân bản tập hợp", "Xoá tập hợp"],
      correct: 0, explanation: "Iterator tách logic duyệt khỏi tập hợp, ẩn cách lưu trữ (mảng, list, cây...)." },
    { q: "Hai phương thức cốt lõi của một iterator là gì?",
      options: ["hasNext() và next()", "add() và remove()", "open() và close()", "get() và set()"],
      correct: 0, explanation: "hasNext() kiểm tra còn phần tử; next() lấy phần tử kế tiếp." },
    { q: "Lợi ích của Iterator khi có nhiều loại tập hợp khác nhau?",
      options: ["Client duyệt mọi tập hợp bằng cùng một giao diện dù cấu trúc khác nhau",
        "Bắt buộc mọi tập hợp dùng mảng", "Tăng tốc gấp đôi", "Loại bỏ vòng lặp"],
      correct: 0, explanation: "Ví dụ duyệt thực đơn dạng mảng và dạng ArrayList bằng cùng một cách." }
  ],
  "mediator": [
    { q: "Mediator làm giảm điều gì giữa các đối tượng?",
      options: ["Phụ thuộc chằng chịt nhiều-nhiều (mọi object nối trực tiếp nhau)",
        "Số lượng đối tượng", "Dung lượng bộ nhớ", "Số dòng code luôn giảm"],
      correct: 0, explanation: "Các đối tượng giao tiếp qua mediator trung tâm thay vì tham chiếu chéo lẫn nhau." },
    { q: "Trong ví dụ phòng chat, mediator là gì?",
      options: ["ChatRoom điều phối tin nhắn giữa các user", "Một user đặc biệt",
        "Cơ sở dữ liệu", "Giao thức mạng"],
      correct: 0, explanation: "User gửi tới ChatRoom; ChatRoom phân phối, user không nối trực tiếp nhau." },
    { q: "Rủi ro của Mediator nếu lạm dụng là gì?",
      options: ["Mediator phình to thành 'god object' ôm quá nhiều logic",
        "Không có rủi ro", "Làm chậm mạng", "Mất khả năng test"],
      correct: 0, explanation: "Dồn hết điều phối vào một chỗ có thể khiến mediator trở nên phức tạp khó bảo trì." }
  ],
  "memento": [
    { q: "Memento dùng để làm gì?",
      options: ["Lưu và khôi phục trạng thái của đối tượng mà không phá vỡ đóng gói",
        "Tạo đối tượng mới", "Duyệt tập hợp", "Đổi interface"],
      correct: 0, explanation: "Memento chụp lại trạng thái nội bộ để sau này khôi phục (undo)." },
    { q: "Ba vai trò trong Memento là gì?",
      options: ["Originator, Memento, Caretaker", "Model, View, Controller",
        "Sender, Receiver, Invoker", "Subject, Observer, Mediator"],
      correct: 0, explanation: "Originator tạo/khôi phục memento; Caretaker giữ các memento; Memento lưu state." },
    { q: "Vì sao Caretaker không nên đọc nội dung Memento?",
      options: ["Để giữ đóng gói — chỉ Originator hiểu và dùng được trạng thái bên trong",
        "Vì memento bị mã hoá", "Vì memento rỗng", "Vì lý do hiệu năng"],
      correct: 0, explanation: "Caretaker chỉ lưu trữ mờ (opaque); chi tiết state chỉ Originator biết." }
  ],
  "observer": [
    { q: "Observer thiết lập quan hệ gì?",
      options: ["Một-nhiều: khi subject đổi, mọi observer tự được thông báo", "Một-một cố định",
        "Nhiều-nhiều bắt buộc", "Không có quan hệ"],
      correct: 0, explanation: "Subject giữ danh sách observer và notify() khi trạng thái thay đổi." },
    { q: "Lợi ích chính của Observer là gì?",
      options: ["Ghép lỏng (loose coupling) giữa subject và observer", "Tăng tốc CPU",
        "Giảm bộ nhớ", "Đảm bảo một thể hiện"],
      correct: 0, explanation: "Subject chỉ biết observer qua interface, thêm/bớt observer tự do lúc chạy." },
    { q: "Ví dụ trạm thời tiết minh hoạ Observer thế nào?",
      options: ["WeatherData phát số liệu, các bảng hiển thị (observer) tự cập nhật khi có dữ liệu mới",
        "Bảng hiển thị tự hỏi liên tục (polling)", "Chỉ một bảng nhận được", "Dữ liệu lưu file"],
      correct: 0, explanation: "Push model: subject chủ động đẩy cập nhật tới mọi observer đã đăng ký." }
  ],
  "state": [
    { q: "State pattern thay đổi hành vi đối tượng dựa trên điều gì?",
      options: ["Trạng thái nội bộ hiện tại (mỗi trạng thái là một lớp riêng)",
        "Loại tham số truyền vào", "Thời gian", "Ngẫu nhiên"],
      correct: 0, explanation: "Mỗi trạng thái đóng gói hành vi riêng; đối tượng uỷ quyền cho state hiện tại." },
    { q: "State pattern giúp tránh điều gì?",
      options: ["Khối if/switch khổng lồ theo cờ trạng thái rải khắp nơi", "Việc dùng interface",
        "Việc tạo đối tượng", "Đệ quy"],
      correct: 0, explanation: "Logic chuyển trạng thái nằm trong từng lớp state, thay cho điều kiện lồng nhau." },
    { q: "Máy bán kẹo gumball chuyển trạng thái thế nào?",
      options: ["NoQuarter → HasQuarter → Sold → SoldOut... theo hành động của người dùng",
        "Luôn ở một trạng thái", "Đổi ngẫu nhiên", "Không có trạng thái"],
      correct: 0, explanation: "Mỗi hành động (bỏ xu, xoay tay) đưa máy sang trạng thái tương ứng khác." }
  ],
  "strategy": [
    { q: "Strategy pattern cho phép làm gì?",
      options: ["Đổi thuật toán (hành vi) lúc chạy bằng cách hoán đổi đối tượng chiến lược",
        "Đảm bảo một thể hiện", "Lưu lịch sử trạng thái", "Duyệt cây"],
      correct: 0, explanation: "Đóng gói từng thuật toán thành lớp riêng, đối tượng dùng có thể đổi qua lại." },
    { q: "Nguyên tắc thiết kế nào Strategy đề cao?",
      options: ["Ưu tiên composition hơn inheritance", "Ưu tiên kế thừa sâu",
        "Global state", "Một thể hiện duy nhất"],
      correct: 0, explanation: "Vịt 'có một' hành vi bay/kêu (composition) thay vì kế thừa cứng." },
    { q: "Con vịt đổi hành vi bay lúc chạy nhờ cái gì?",
      options: ["setFlyBehavior() gán một FlyBehavior khác vào field", "Sửa lại lớp Duck",
        "Tạo con vịt mới", "Dùng if/else"],
      correct: 0, explanation: "Duck giữ tham chiếu FlyBehavior; đổi field là đổi hành vi ngay tức thì." }
  ],
  "template-method": [
    { q: "Template Method định nghĩa cái gì trong lớp cha?",
      options: ["Khung (bộ xương) thuật toán, để lớp con điền vài bước cụ thể",
        "Toàn bộ chi tiết", "Không gì cả", "Chỉ dữ liệu"],
      correct: 0, explanation: "Phương thức template cố định thứ tự các bước; bước biến đổi để lớp con override." },
    { q: "Nguyên tắc 'Hollywood' (Đừng gọi chúng tôi, chúng tôi sẽ gọi bạn) liên quan gì?",
      options: ["Lớp cha điều khiển luồng và gọi xuống các bước của lớp con",
        "Lớp con gọi lớp cha tuỳ ý", "Client gọi mọi bước", "Không liên quan"],
      correct: 0, explanation: "Khung ở lớp cha chủ động gọi các hook/bước do lớp con cung cấp." },
    { q: "Ví dụ pha Cà phê & Trà minh hoạ thế nào?",
      options: ["Cùng khung (đun nước → pha → rót → thêm) nhưng khác bước 'pha' và 'thêm'",
        "Hai thuật toán hoàn toàn khác nhau", "Chỉ pha được cà phê", "Không dùng lớp cha"],
      correct: 0, explanation: "Các bước chung ở lớp cha; brew()/addCondiments() do lớp con định nghĩa riêng." }
  ],
  "visitor": [
    { q: "Visitor cho phép làm gì mà không sửa lớp phần tử?",
      options: ["Thêm thao tác (operation) mới lên một tập cấu trúc đối tượng cố định",
        "Thêm phần tử mới dễ dàng", "Đảm bảo một thể hiện", "Đổi interface"],
      correct: 0, explanation: "Đưa thao tác mới vào một Visitor riêng; phần tử chỉ cần accept(visitor)." },
    { q: "Kỹ thuật 'double dispatch' trong Visitor nghĩa là gì?",
      options: ["element.accept(visitor) rồi visitor.visit(element) — chọn hàm theo cả 2 loại",
        "Gọi hàm hai lần", "Chạy hai luồng", "Hai visitor cùng lúc"],
      correct: 0, explanation: "Kết quả phụ thuộc đồng thời loại phần tử VÀ loại visitor." },
    { q: "Điểm yếu của Visitor là gì?",
      options: ["Thêm một loại phần tử mới đòi hỏi sửa mọi visitor", "Không thêm được thao tác",
        "Luôn chậm", "Không dùng được với cây"],
      correct: 0, explanation: "Visitor dễ thêm thao tác nhưng khó thêm loại phần tử (đối lập với Composite)." }
  ],

  /* ============== MODERN — Phổ biến ============== */
  "dependency-injection": [
    { q: "Dependency Injection nghĩa là gì?",
      options: ["Cung cấp phụ thuộc từ bên ngoài thay vì để đối tượng tự new ra",
        "Tự tạo mọi phụ thuộc bên trong", "Xoá phụ thuộc", "Dùng biến toàn cục"],
      correct: 0, explanation: "Phụ thuộc được 'tiêm' qua constructor/setter → dễ thay thế & test." },
    { q: "Lợi ích lớn nhất của DI cho testing là gì?",
      options: ["Dễ thay phụ thuộc thật bằng mock/stub khi test", "Chạy test nhanh gấp đôi",
        "Không cần test", "Ẩn lỗi"],
      correct: 0, explanation: "Vì phụ thuộc tiêm từ ngoài, test có thể truyền bản giả (mock) dễ dàng." },
    { q: "DI hỗ trợ nguyên tắc SOLID nào rõ nhất?",
      options: ["Dependency Inversion Principle", "Single Responsibility", "Liskov Substitution", "Interface Segregation"],
      correct: 0, explanation: "Phụ thuộc vào abstraction và nhận nó từ ngoài chính là Dependency Inversion." }
  ],
  "repository": [
    { q: "Repository pattern che giấu điều gì?",
      options: ["Chi tiết nguồn dữ liệu (DB, API, bộ nhớ) sau một interface truy cập chung",
        "Giao diện người dùng", "Logic nghiệp vụ", "Mạng"],
      correct: 0, explanation: "Client thao tác qua interface giống thao tác một 'bộ sưu tập', không biết nguồn thật." },
    { q: "Lợi ích của Repository khi đổi nguồn dữ liệu?",
      options: ["Đổi từ in-memory sang API/DB mà không sửa code nghiệp vụ dùng nó",
        "Bắt buộc phải sửa client", "Tăng tốc CPU", "Giảm bộ nhớ"],
      correct: 0, explanation: "Chỉ cần một implementation repository mới; phần gọi vẫn dùng cùng interface." },
    { q: "Repository thường trả về gì?",
      options: ["Các đối tượng domain (entity) chứ không phải bản ghi thô/SQL", "Chuỗi SQL",
        "Kết nối DB", "HTML"],
      correct: 0, explanation: "Repository ánh xạ dữ liệu thô thành đối tượng domain cho tầng nghiệp vụ." }
  ],
  "mvc": [
    { q: "Trong MVC, Controller làm nhiệm vụ gì?",
      options: ["Nhận input người dùng, cập nhật Model và chọn View", "Lưu dữ liệu",
        "Vẽ giao diện", "Kết nối mạng"],
      correct: 0, explanation: "Controller điều phối: xử lý hành động, đổi Model, chọn cách hiển thị." },
    { q: "Model KHÔNG nên biết điều gì?",
      options: ["Chi tiết View/giao diện hiển thị nó", "Dữ liệu của chính nó",
        "Quy tắc nghiệp vụ", "Trạng thái"],
      correct: 0, explanation: "Model độc lập với View; View quan sát Model, không phải ngược lại." },
    { q: "Lợi ích chính của việc tách MVC là gì?",
      options: ["Tách mối quan tâm → dễ test, thay View/logic độc lập", "Chạy nhanh hơn tuyệt đối",
        "Giảm số file", "Không cần interface"],
      correct: 0, explanation: "Separation of concerns giúp bảo trì, thay UI hoặc logic mà ít ảnh hưởng lẫn nhau." }
  ],
  "pubsub": [
    { q: "Pub/Sub khác Observer cổ điển ở điểm nào?",
      options: ["Publisher và subscriber không biết nhau, giao tiếp qua event bus/broker trung gian",
        "Giống hệt nhau", "Pub/Sub luôn đồng bộ", "Subscriber gọi trực tiếp publisher"],
      correct: 0, explanation: "Event bus đứng giữa nên hai bên tách rời hoàn toàn, không giữ tham chiếu nhau." },
    { q: "Đơn vị định tuyến trong Pub/Sub thường là gì?",
      options: ["Topic/kênh (channel) của sự kiện", "Địa chỉ IP", "Tên lớp", "ID người dùng"],
      correct: 0, explanation: "Publisher phát vào một topic; ai subscribe topic đó sẽ nhận được." },
    { q: "Ưu điểm của kiến trúc Pub/Sub là gì?",
      options: ["Ghép lỏng và dễ mở rộng số bên phát/nhận độc lập", "Bảo mật tuyệt đối",
        "Không bao giờ mất tin", "Luôn nhanh nhất"],
      correct: 0, explanation: "Thêm/bớt subscriber hay publisher không ảnh hưởng bên còn lại." }
  ],
  "null-object": [
    { q: "Null Object pattern thay thế cái gì?",
      options: ["Giá trị null bằng một đối tượng 'rỗng' hợp lệ có hành vi mặc định (không làm gì)",
        "Đối tượng thật bằng Singleton", "Vòng lặp bằng đệ quy", "Interface bằng lớp cụ thể"],
      correct: 0, explanation: "Null Object implement cùng interface nhưng hành vi trung tính, an toàn." },
    { q: "Lợi ích chính của Null Object là gì?",
      options: ["Loại bỏ các kiểm tra if (x != null) rải rác", "Tăng tốc độ",
        "Giảm bộ nhớ", "Ẩn hệ thống con"],
      correct: 0, explanation: "Client gọi phương thức bình thường, không cần phòng null → code sạch hơn." },
    { q: "Rủi ro của Null Object là gì?",
      options: ["Che giấu lỗi thật sự khi lẽ ra cần biết 'không có dữ liệu'",
        "Luôn ném ngoại lệ", "Tốn RAM lớn", "Không dùng được interface"],
      correct: 0, explanation: "Nếu 'không có gì' là bất thường, im lặng bỏ qua có thể giấu bug." }
  ],

  /* ============== MODERN — Kiến trúc backend ============== */
  "cqrs": [
    { q: "CQRS tách rời điều gì?",
      options: ["Đường ghi (Command) và đường đọc (Query) thành hai mô hình riêng",
        "Client và server", "Model và View", "Trừu tượng và hiện thực"],
      correct: 0, explanation: "Command thay đổi trạng thái; Query chỉ đọc — tối ưu độc lập hai phía." },
    { q: "Vì sao tách đọc/ghi lại có lợi?",
      options: ["Mỗi phía tối ưu riêng (đọc scale rộng, ghi đảm bảo nhất quán)",
        "Giảm số dòng code", "Bảo mật tự động", "Không cần database"],
      correct: 0, explanation: "Read model có thể phi chuẩn hoá để đọc nhanh; write model tập trung tính đúng đắn." },
    { q: "CQRS thường đi kèm pattern nào?",
      options: ["Event Sourcing", "Singleton", "Adapter", "Iterator"],
      correct: 0, explanation: "Ghi sinh event; read model dựng từ event → CQRS + Event Sourcing rất hợp nhau." }
  ],
  "event-sourcing": [
    { q: "Event Sourcing lưu trữ cái gì làm nguồn sự thật?",
      options: ["Chuỗi các sự kiện đã xảy ra, thay vì chỉ trạng thái hiện tại",
        "Ảnh chụp màn hình", "Chỉ trạng thái cuối", "File log tạm"],
      correct: 0, explanation: "Trạng thái được dựng lại bằng cách phát lại (replay) toàn bộ sự kiện." },
    { q: "Muốn có trạng thái hiện tại trong Event Sourcing ta làm gì?",
      options: ["Phát lại (replay) các event từ đầu, hoặc từ một snapshot", "Đọc cột 'state' trong DB",
        "Không lấy được", "Gọi Singleton"],
      correct: 0, explanation: "Trạng thái là kết quả gấp (fold) chuỗi event; snapshot giúp tăng tốc." },
    { q: "Ưu điểm nổi bật của Event Sourcing là gì?",
      options: ["Có lịch sử đầy đủ (audit), khôi phục về thời điểm bất kỳ",
        "Tốn ít dung lượng nhất", "Đơn giản nhất để triển khai", "Không cần xử lý event cũ"],
      correct: 0, explanation: "Mọi thay đổi được ghi lại → truy vết, debug, time-travel; đổi lại phức tạp hơn." }
  ],
  "unit-of-work": [
    { q: "Unit of Work làm gì?",
      options: ["Gom mọi thay đổi trong một phiên rồi commit chúng trong một giao dịch",
        "Tạo một thể hiện", "Duyệt tập hợp", "Đổi interface"],
      correct: 0, explanation: "Theo dõi đối tượng thêm/sửa/xoá rồi ghi tất cả một lần khi commit()." },
    { q: "Lợi ích chính của Unit of Work là gì?",
      options: ["Đảm bảo tính nhất quán và giảm số lần ghi DB (một transaction)",
        "Tăng RAM", "Ẩn giao diện", "Tạo nhiều kết nối"],
      correct: 0, explanation: "Hoặc tất cả thay đổi được ghi, hoặc rollback toàn bộ — giữ nhất quán." },
    { q: "Unit of Work thường phối hợp với pattern nào?",
      options: ["Repository", "Flyweight", "Interpreter", "Visitor"],
      correct: 0, explanation: "Repository quản lý từng loại entity; Unit of Work điều phối commit chung." }
  ],
  "service-locator": [
    { q: "Service Locator hoạt động thế nào?",
      options: ["Một registry trung tâm nơi đăng ký và tra cứu service theo khoá",
        "Tự new mọi service", "Xoá service cũ", "Chỉ dùng cho UI"],
      correct: 0, explanation: "Client hỏi locator lấy service theo tên/khoá thay vì tự khởi tạo." },
    { q: "Service Locator khác Dependency Injection ở điểm nào?",
      options: ["SL: client chủ động 'kéo' service; DI: phụ thuộc được 'đẩy' vào client",
        "Giống hệt nhau", "SL không dùng interface", "DI dùng registry, SL thì không"],
      correct: 0, explanation: "Pull (locator) vs push (injection) — DI làm phụ thuộc rõ ràng hơn." },
    { q: "Nhược điểm thường bị phê phán của Service Locator là gì?",
      options: ["Giấu phụ thuộc (không nhìn thấy qua chữ ký) → khó test và khó theo dõi",
        "Quá nhanh", "Không lưu được service", "Bắt buộc dùng Singleton"],
      correct: 0, explanation: "Phụ thuộc bị ẩn bên trong body, nhiều người coi đây là anti-pattern so với DI." }
  ],

  /* ============== MODERN — Tiện ích ============== */
  "object-pool": [
    { q: "Object Pool tối ưu điều gì?",
      options: ["Tái sử dụng đối tượng đắt đỏ thay vì tạo/huỷ liên tục",
        "Bảo mật", "Giao diện", "Định tuyến sự kiện"],
      correct: 0, explanation: "Giữ sẵn một 'bể' đối tượng; mượn khi cần, trả lại khi xong." },
    { q: "Khi nào Object Pool đáng dùng?",
      options: ["Khi tạo đối tượng tốn kém và được dùng lại thường xuyên (kết nối DB, thread)",
        "Khi đối tượng rất rẻ", "Khi chỉ cần một thể hiện", "Khi không tái dùng"],
      correct: 0, explanation: "Chi phí khởi tạo cao + tần suất dùng lớn → pool giảm overhead rõ rệt." },
    { q: "Rủi ro khi dùng Object Pool là gì?",
      options: ["Quên reset trạng thái đối tượng khi trả về → rò rỉ dữ liệu cũ",
        "Luôn chậm hơn", "Không thể mở rộng", "Bắt buộc dùng mạng"],
      correct: 0, explanation: "Đối tượng tái dùng phải được làm sạch, nếu không mang theo state cũ gây bug." }
  ],
  "specification": [
    { q: "Specification pattern dùng để làm gì?",
      options: ["Đóng gói quy tắc nghiệp vụ thành đối tượng có thể ghép AND/OR/NOT để lọc",
        "Tạo đối tượng", "Duyệt tập hợp", "Lưu trạng thái"],
      correct: 0, explanation: "Mỗi spec trả về true/false; ghép chúng thành điều kiện phức tạp tái dùng được." },
    { q: "Lợi ích của việc tổ hợp specification là gì?",
      options: ["Tái sử dụng và kết hợp quy tắc mà không nhân bản logic điều kiện",
        "Tăng tốc CPU", "Giảm RAM", "Ẩn giao diện"],
      correct: 0, explanation: "AndSpec/OrSpec/NotSpec ghép các quy tắc nhỏ thành quy tắc lớn linh hoạt." },
    { q: "Phương thức đặc trưng của một Specification là gì?",
      options: ["isSatisfiedBy(candidate) trả về boolean", "execute()", "next()", "clone()"],
      correct: 0, explanation: "isSatisfiedBy kiểm tra một ứng viên có thoả quy tắc hay không." }
  ],
  "lazy-loading": [
    { q: "Lazy Loading nghĩa là gì?",
      options: ["Hoãn khởi tạo/nạp tài nguyên đến lần đầu thực sự cần dùng",
        "Nạp mọi thứ ngay từ đầu", "Không bao giờ nạp", "Nạp ngẫu nhiên"],
      correct: 0, explanation: "Tài nguyên nặng chỉ được tạo khi truy cập lần đầu → khởi động nhanh, tiết kiệm." },
    { q: "Lazy Loading giúp cải thiện điều gì?",
      options: ["Thời gian khởi động và mức dùng tài nguyên khi chưa cần",
        "Bảo mật", "Độ chính xác dữ liệu", "Khả năng undo"],
      correct: 0, explanation: "Không trả chi phí cho thứ chưa dùng; chỉ tốn khi thật sự truy cập." },
    { q: "Rủi ro của Lazy Loading là gì?",
      options: ["Độ trễ ở lần truy cập đầu, và vấn đề đồng thời (thread-safety)",
        "Luôn tốn RAM gấp đôi", "Không dùng được với DB", "Mất dữ liệu"],
      correct: 0, explanation: "Lần đầu chậm hơn; nếu nhiều luồng cùng khởi tạo cần đồng bộ cẩn thận." }
  ],
  "module-pattern": [
    { q: "Module Pattern dùng kỹ thuật gì để tạo trạng thái riêng tư?",
      options: ["Closure — biến trong hàm không lộ ra ngoài, chỉ trả về API công khai",
        "Kế thừa", "Singleton toàn cục", "Biến global"],
      correct: 0, explanation: "Hàm bao đóng giữ biến private; chỉ những gì được return mới truy cập được." },
    { q: "Module Pattern giúp tránh vấn đề gì trong JavaScript?",
      options: ["Ô nhiễm không gian tên toàn cục (global namespace pollution)",
        "Đệ quy vô hạn", "Rò rỉ bộ nhớ luôn xảy ra", "Chậm CPU"],
      correct: 0, explanation: "Gói biến vào module thay vì rải biến ra global scope." },
    { q: "Cấu trúc điển hình của Module Pattern là gì?",
      options: ["IIFE (hàm tự gọi) trả về object chứa các phương thức công khai",
        "Một class kế thừa", "Một mảng phẳng", "Một vòng lặp"],
      correct: 0, explanation: "(function(){ let priv; return { publicFn(){} }; })() — private ẩn, public lộ." }
  ],

  /* ============== MODERN — Async / JavaScript ============== */
  "middleware": [
    { q: "Middleware/Pipeline xử lý request thế nào?",
      options: ["Cho request đi qua một chuỗi hàm, mỗi hàm có thể xử lý rồi gọi next()",
        "Xử lý tất cả cùng lúc", "Chỉ hàm cuối xử lý", "Bỏ qua request"],
      correct: 0, explanation: "Mỗi middleware làm phần việc của mình rồi chuyển tiếp cho middleware kế." },
    { q: "Vai trò của next() trong middleware là gì?",
      options: ["Chuyển quyền điều khiển sang middleware tiếp theo trong chuỗi",
        "Kết thúc chương trình", "Quay lại middleware trước", "Tạo request mới"],
      correct: 0, explanation: "Không gọi next() thì chuỗi dừng; gọi next() để đi tiếp." },
    { q: "Ưu điểm của kiến trúc middleware (như Express) là gì?",
      options: ["Tách các mối quan tâm (log, auth, parse...) thành các lớp cắm-rút được",
        "Chạy nhanh hơn mọi cách khác", "Không cần xử lý lỗi", "Giảm RAM"],
      correct: 0, explanation: "Cross-cutting concern thành middleware độc lập, dễ thêm/bớt/sắp xếp lại." }
  ],
  "reactive-streams": [
    { q: "Reactive Streams mô hình dữ liệu như thế nào?",
      options: ["Luồng (stream) các giá trị theo thời gian, biến đổi qua map/filter tới subscriber",
        "Một giá trị đơn tĩnh", "Bảng dữ liệu cố định", "File tuần tự"],
      correct: 0, explanation: "Dữ liệu 'chảy' qua các toán tử rồi tới người đăng ký (kiểu RxJS)." },
    { q: "Toán tử map trên một stream làm gì?",
      options: ["Biến đổi mỗi giá trị phát ra thành giá trị mới", "Lọc bỏ giá trị",
        "Dừng stream", "Nhân đôi subscriber"],
      correct: 0, explanation: "map biến đổi từng phần tử; filter mới là loại bỏ theo điều kiện." },
    { q: "'Backpressure' trong reactive streams là gì?",
      options: ["Cơ chế xử lý khi producer phát nhanh hơn consumer tiêu thụ",
        "Lỗi mạng", "Một loại subscriber", "Cách nén dữ liệu"],
      correct: 0, explanation: "Backpressure điều tiết tốc độ để consumer không bị quá tải." }
  ],
  "promise-async": [
    { q: "Một Promise có các trạng thái nào?",
      options: ["pending → fulfilled hoặc rejected", "start → stop", "open → close", "true → false"],
      correct: 0, explanation: "Promise bắt đầu pending, rồi chuyển sang fulfilled (resolve) hoặc rejected (reject)." },
    { q: "Trạng thái của Promise có thể đổi lại sau khi đã settled không?",
      options: ["Không — một khi fulfilled/rejected thì cố định (immutable)", "Có, đổi tự do",
        "Chỉ đổi một lần nữa", "Tuỳ trình duyệt"],
      correct: 0, explanation: "Promise chỉ settle đúng một lần; sau đó kết quả không đổi." },
    { q: "async/await liên quan gì tới Promise?",
      options: ["await tạm dừng hàm async đến khi Promise settle, viết bất đồng bộ như đồng bộ",
        "Chúng không liên quan", "await tạo Promise mới mỗi dòng", "async biến hàm thành đồng bộ thật"],
      correct: 0, explanation: "Hàm async trả về Promise; await 'mở gói' giá trị khi Promise hoàn tất." }
  ]
};
